/**
 * The only place in the application that names a media file.
 *
 * Every path resolves to a derivative in `public/media/`, generated by
 * `.olympus/tools/prepare_media.py` from the read-only originals in `media/`.
 * Nothing here points at `media/` directly.
 *
 * The `field` values are *measured*, not chosen: the pipeline samples each course
 * photograph's border ring and writes the result into
 * `.olympus/evidence/asset-manifest.json`. Beat 5 paints that colour behind the plate so the
 * photograph has no visible edge. Course 5's `#365862` sits RGB-7 from the brand slate
 * `#335C67`, which is where the whole idea came from.
 *
 * To change a crop, a size or a field colour: edit the tool and re-run it. Never hand-edit
 * `public/media/`, and never add a second place that names a file.
 */

const base = import.meta.env.BASE_URL

const url = (name: string) => `${base}media/${name}`

export interface Course {
  id: string
  /** Roman numeral shown in the list. */
  numeral: string
  name: string
  /** The two or three things on the plate, in the order they read. */
  detail: string
  image: string
  thumb: string
  width: number
  height: number
  /** Measured background of the photograph. Painted behind it so the edge disappears. */
  field: string
  alt: string
}

/** Beat 5. Six courses, one per distinct subject in the supplied set. */
export const courses: Course[] = [
  {
    id: 'flatbread',
    numeral: 'I',
    name: 'Flatbread',
    detail: 'smoked butter · za’atar · green oil',
    image: url('course-1.webp'),
    thumb: url('course-1-thumb.webp'),
    width: 896,
    height: 672,
    field: '#374E53',
    alt: 'Blistered flatbread with za’atar and green oil on a teal oval dish, smoked butter in a small bowl beside it, on slate.',
  },
  {
    id: 'beetroot',
    numeral: 'II',
    name: 'Salt-baked beetroot',
    detail: 'labneh · hazelnut · herb oil',
    image: url('course-2.webp'),
    thumb: url('course-2-thumb.webp'),
    width: 1000,
    height: 750,
    field: '#545B56',
    alt: 'Salt-baked beetroot on labneh with hazelnuts and herb oil, seen from above on a teal plate against dark slate.',
  },
  {
    id: 'seabass',
    numeral: 'III',
    name: 'Charcoal sea bass',
    detail: 'fennel · preserved lemon · dill',
    image: url('course-3.webp'),
    thumb: url('course-3-thumb.webp'),
    width: 896,
    height: 672,
    field: '#3F382F',
    alt: 'Charred sea bass under shaved fennel and dill on a teal oval plate, on a worn wooden table.',
  },
  {
    id: 'aubergine',
    numeral: 'IV',
    name: 'Aubergine',
    detail: 'tahini · pomegranate molasses · sumac',
    image: url('course-4.webp'),
    thumb: url('course-4-thumb.webp'),
    width: 1000,
    height: 750,
    field: '#32484D',
    alt: 'A roasted aubergine half with tahini, sumac and herbs on a cream plate, on slate.',
  },
  {
    id: 'duck',
    numeral: 'V',
    name: 'Dry-aged duck',
    detail: 'parsnip · blackcurrant · basil',
    image: url('course-5.webp'),
    thumb: url('course-5-thumb.webp'),
    width: 1000,
    height: 750,
    // Measured #365862 against brand slate #335C67 — RGB distance 7. The seam is invisible
    // here, which is why this is the course a visitor meets first.
    field: '#365862',
    alt: 'Sliced duck breast with charred parsnip and blackcurrant, seen from above on a teal plate against a flat slate-blue ground.',
  },
  {
    id: 'quince',
    numeral: 'VI',
    name: 'Saffron quince',
    detail: 'yoghurt · pistachio · brittle',
    image: url('course-6.webp'),
    thumb: url('course-6-thumb.webp'),
    width: 896,
    height: 672,
    field: '#403E38',
    alt: 'Saffron-poached quince with thick yoghurt, pistachio and a shard of brittle in a cream bowl, lacquered panelling behind.',
  },
]

/** Course 5 — the one whose measured field matches the brand slate. */
export const defaultCourseIndex = 4

export const media = {
  street: {
    src: url('street.webp'),
    width: 1200,
    height: 675,
    alt: 'The SAVRA shopfront at dusk on a Vienna side street: a dark slate frame around a warmly lit dining room, one figure passing on the cobbles.',
  },
  roomPoster: {
    src: url('room-poster.webp'),
    width: 1200,
    height: 675,
    alt: 'The dining room before service: lacquered oxblood panelling, brass inlay, slate tables laid with linen, every chair empty.',
  },
  clip: {
    src: url('room.mp4'),
    poster: url('room-poster-frame.webp'),
    // Intrinsic box, so a `preload="none"` video does not start at the 300x150 default and
    // reflow a full-bleed element by ~120px when the poster resolves.
    width: 1120,
    height: 617,
    alt: 'A slow move in toward a single lamp on a table laid for two.',
  },
  materialWeave: {
    src: url('material-weave.webp'),
    width: 900,
    height: 600,
    alt: 'Oatmeal linen falling over a slate edge, met by a brass line and black oak.',
  },
  materialWeaveDetail: { src: url('material-weave-detail.webp'), width: 322, height: 322, alt: '' },
  materialSetting: {
    src: url('material-setting.webp'),
    width: 700,
    height: 933,
    alt: 'A place setting on slate: a cream plate on a linen runner, cutlery engraved SAVRA, a smoked-glass lamp at the edge of frame.',
  },
  materialSettingDetail: { src: url('material-setting-detail.webp'), width: 358, height: 358, alt: '' },
  hands: {
    src: url('hands.webp'),
    width: 801,
    height: 1068,
    alt: 'A chef alone at the pass under a single pendant lamp, both hands resting either side of a white plate holding one leaf.',
  },
  door: {
    src: url('door.webp'),
    width: 1200,
    height: 675,
    alt: 'A dark door standing ajar in a slate wall, warm light spilling from the room beyond onto a single laid table.',
  },
  roomLit: {
    src: url('room-lit.webp'),
    width: 900,
    height: 600,
    alt: 'The dining room lit and laid, seen straight down the centre aisle.',
  },
  table: {
    src: url('table.webp'),
    width: 760,
    height: 1013,
    alt: 'One slate table set for two against a dark panelled wall, a single lamp lit between the two settings.',
  },
} as const
