export const skills = [
  { id: 'olympus-design-director', name: 'Olympus Design Director', phase: 'always', group: 'Orchestration', defaultOn: true, description: 'Owns the brief, routes work, and enforces approval gates.', runtimePrompt: 'Act as the single design director. Maintain one interpretation of the brief, activate only relevant capabilities, and make dependencies and approval boundaries explicit.' },
  { id: 'taste-first-experience-design', name: 'Taste-First Experience Design', phase: 'direct', group: 'Experience', defaultOn: false, description: 'Turns visual preference evidence into editable Creative DNA, plain-language choices, and a bounded mission setup.', runtimePrompt: 'Elicit taste through concrete visual choices, preserve provenance and uncertainty, produce an editable Style Profile, explain consequences in plain language, recommend the smallest capable squad, and progressively disclose advanced controls without hiding cost or permissions.' },
  { id: 'ethical-gamification-systems', name: 'Ethical Gamification Systems', phase: 'direct', group: 'Progression', defaultOn: false, description: 'Creates meaningful missions, mastery, rewards, and collections with explicit spend and anti-coercion safeguards.', runtimePrompt: 'Reward creative value, mastery, and reusable outcomes rather than attention or token spend. Make costs and evidence states explicit; reject false urgency, streak punishment, automatic paid retries, misleading status, and mechanics that add complexity without user benefit.' },
  { id: 'agent-identity-and-portfolio', name: 'Agent Identity and Portfolio', phase: 'prepare', group: 'Agents', defaultOn: false, description: 'Defines consistent agent identities, transparent inventory, and evidence-backed marketplace portfolios.', runtimePrompt: 'Keep agent identity memorable but truthful. Specify a reproducible avatar bible, capability and configuration limits, typed inventory availability, and portfolio claims linked to inspectable evidence. Reject fabricated achievements, endorsements, credentials, or deceptive persona claims.' },
  { id: 'ux-evidence-audit', name: 'UX Evidence Audit', phase: 'diagnose', group: 'Evidence', defaultOn: true, description: 'Diagnoses source, browser, responsive, accessibility, and content evidence.', runtimePrompt: 'Diagnose before prescribing. Separate observations from inferences, prioritize the five highest-leverage issues, and identify affected users.' },
  { id: 'reference-deconstruction', name: 'Reference Deconstruction', phase: 'diagnose', group: 'Evidence', defaultOn: true, description: 'Extracts transferable visual logic without copying expression.', runtimePrompt: 'Analyze references as systems: composition, type, material, interaction, responsive behavior, risks, and transferable principles. Do not copy distinctive expression.' },
  { id: 'concept-studio', name: 'Concept Studio', phase: 'direct', group: 'Direction', defaultOn: true, description: 'Creates materially distinct design directions.', runtimePrompt: 'Generate exactly three materially different directions when concepts are requested. Distinguish structure, hierarchy, media, motion, mobile behavior, assets, and risk—not only color.' },
  { id: 'award-rubric', name: 'Award Rubric', phase: 'direct', group: 'Direction', defaultOn: false, description: 'Scores frozen concepts without silently redesigning them.', runtimePrompt: 'Critique independently. Score design, usability, creativity, content, and delivery risk; identify defects without merging or rewriting the proposed directions.' },
  { id: 'asset-director', name: 'Asset Director', phase: 'prepare', group: 'Production', defaultOn: false, description: 'Plans required media, provenance, rights, and fallbacks.', runtimePrompt: 'Define an explicit asset manifest. State what the user should provide, provenance and rights needs, generation cost, and fallback before proposing external production.' },
  { id: 'webgl-experience', name: 'WebGL Experience', phase: 'prepare', group: 'Production', defaultOn: false, description: 'Tests whether 3D has communication value and specifies a bounded fallback.', runtimePrompt: 'Use WebGL only when it communicates something that 2D cannot. Bound performance, lifecycle, mobile, loading, accessibility, reduced motion, and static fallback.' },
  { id: 'awwwards-web-design', name: 'Awwwards Web Design', phase: 'build', group: 'Craft', defaultOn: false, description: 'Adds premium editorial craft after hierarchy is stable.', runtimePrompt: 'Raise visual craft after hierarchy is accepted. Protect clarity, accessibility, responsive behavior, and performance while creating a distinctive editorial experience.' },
  { id: 'ui-ux', name: 'UI/UX Quality', phase: 'diagnose', group: 'Craft', defaultOn: true, description: 'Establishes product cognition, task journeys, progressive disclosure, recovery states, mobile priorities, and frontend governance.', runtimePrompt: 'Act as the product-cognition and UI/UX quality gate. Establish the user, business objects, surface type, primary task, first decision, success and recovery paths, mobile priority, vocabulary, and verification plan before visual execution. Prevent card walls, business-object soup, raw technical copy, missing states, and mechanical mobile stacking.' },
  { id: 'apple-design', name: 'Apple Design', phase: 'direct', group: 'Craft', defaultOn: true, description: 'Applies Apple-inspired purpose, agency, familiarity, simplicity, typography, material restraint, and fluid interaction principles to the cross-platform desktop experience.', runtimePrompt: 'Treat Apollo as Apple-inspired rather than HIG-compliant. Prioritize purpose, agency, familiarity, simplicity, legible hierarchy, system typography, restrained materials, immediate feedback, spatial consistency, interruptible motion, reduced-motion and reduced-transparency alternatives, and platform-appropriate desktop behavior. Do not imitate proprietary Apple screens or assets.' },
  { id: 'emil-design-eng', name: 'Emil Design Engineering', phase: 'build', group: 'Craft', defaultOn: true, description: 'Polishes component feel, interaction feedback, animation decisions, easing, performance, and invisible interface details.', runtimePrompt: 'Apply Emil Kowalski\'s design-engineering discipline after hierarchy and flows are stable. Decide whether motion is warranted by frequency and purpose; keep frequent and keyboard actions instant, use precise properties and strong easing, preserve interruptibility and reduced motion, constrain motion to transform and opacity where practical, and verify interaction details in slow motion when implemented.' },
  { id: 'impeccable', name: 'Impeccable', phase: 'build', group: 'Craft', defaultOn: false, description: 'Optional production UI craft and bounded finishing pass.', runtimePrompt: 'Use only when explicitly routed for an additional finishing pass. Resolve hierarchy, typography, spacing, states, accessibility, responsive behavior, and purposeful interaction without overriding the approved UI/UX, Apple, or Emil design contracts.' },
  { id: 'gsap-core', name: 'GSAP Core', phase: 'prepare', group: 'Motion', defaultOn: false, description: 'Adds responsive, reduced-motion-aware tweens.', runtimePrompt: 'Use GSAP transforms and built-in eases for purposeful runtime-controlled motion. Honor prefers-reduced-motion and keep content visible without animation.' },
  { id: 'gsap-timeline', name: 'GSAP Timeline', phase: 'prepare', group: 'Motion', defaultOn: false, description: 'Sequences dependent animation beats.', runtimePrompt: 'Use a GSAP timeline only when animation order carries meaning. Keep timing interruptible, readable, and reduced-motion safe.' },
  { id: 'gsap-scrolltrigger', name: 'GSAP ScrollTrigger', phase: 'prepare', group: 'Motion', defaultOn: false, description: 'Controls justified scroll-linked narratives and pinning.', runtimePrompt: 'Use scroll-driven motion only when the narrative requires it. Avoid decorative pinning; specify responsive and reduced-motion alternatives.' },
  { id: 'gsap-react', name: 'GSAP React', phase: 'build', group: 'Motion', defaultOn: false, description: 'Scopes React animation lifecycle and cleanup.', runtimePrompt: 'For React animation, use scoped refs and lifecycle-safe cleanup. Prevent duplicate effects across mounts and strict mode.' },
  { id: 'gsap-frameworks', name: 'GSAP Frameworks', phase: 'build', group: 'Motion', defaultOn: false, description: 'Scopes Vue, Nuxt, Svelte, and SvelteKit animation lifecycle.', runtimePrompt: 'Align GSAP setup and cleanup with the selected non-React framework lifecycle. Scope selectors and remove effects on unmount.' },
  { id: 'gsap-performance', name: 'GSAP Performance', phase: 'verify', group: 'Motion', defaultOn: false, description: 'Finds animation jank and layout-thrashing risk.', runtimePrompt: 'Audit animation performance. Prefer transforms, batch DOM reads and writes, bound will-change, and flag layout thrashing or excessive concurrent effects.' },
  { id: 'gsap-plugins', name: 'GSAP Plugins', phase: 'prepare', group: 'Motion', defaultOn: false, description: 'Routes approved plugin use such as Flip, Draggable, or SplitText.', runtimePrompt: 'Select a GSAP plugin only for a concrete interaction need. Include registration, lifecycle, accessibility, licensing, and a no-plugin fallback.' },
  { id: 'design-analytics', name: 'Design Analytics', phase: 'verify', group: 'Measurement', defaultOn: false, description: 'Connects design hypotheses to a minimal event contract.', runtimePrompt: 'Translate the business goal into a baseline, falsifiable hypothesis, minimal event-property contract, guardrails, and readout plan. Never invent analytics.' },
  { id: 'visual-qa', name: 'Visual QA', phase: 'verify', group: 'Verification', defaultOn: true, description: 'Verifies desktop, mobile, states, runtime, accessibility, and risk.', runtimePrompt: 'Verify the implementation against the approved direction at desktop and mobile, including interaction states, reduced motion, console health, accessibility basics, assets, and performance risks. Limit repair loops to two.' }
];

export const tools = [
  { id: 'web_search', name: 'OpenAI Web Search', kind: 'hosted', usable: true, status: 'Available in live API mode', description: 'Current web evidence through the Responses API.' },
  { id: 'browser_control', name: 'Browser Control', kind: 'local', usable: false, status: 'Codex-hosted adapter', description: 'Page inspection and visual QA; requires a browser automation bridge.' },
  { id: 'figma', name: 'Figma MCP', kind: 'mcp', usable: false, status: 'Requires MCP connection', description: 'Approved frames, variables, components, and exportable assets.' },
  { id: 'posthog', name: 'PostHog MCP', kind: 'mcp', usable: false, status: 'Requires MCP connection', description: 'Read-only baselines, funnels, experiments, and event evidence.' },
  { id: 'higgsfield', name: 'Higgsfield MCP', kind: 'mcp', usable: false, status: 'Requires approval + MCP', description: 'Media generation after an approved asset manifest.' },
  { id: 'chrome_devtools', name: 'Chrome DevTools MCP', kind: 'mcp', usable: false, status: 'Requires MCP connection', description: 'Runtime profiling and targeted performance diagnosis.' }
];

export const plugins = [
  { id: 'browser', name: 'Browser', status: 'Host capability', description: 'Interactive local page inspection and browser QA when the active host exposes it.' },
  { id: 'imagegen', name: 'Image generation', status: 'Host capability', description: 'Raster generation and editing when the host and approvals allow it.' },
  { id: 'documents', name: 'Documents', status: 'Host plugin', description: 'Create, edit, render, and verify Word-compatible documents.' },
  { id: 'pdf', name: 'PDF', status: 'Host plugin', description: 'Read, generate, render, and verify PDF artifacts.' },
  { id: 'presentations', name: 'Presentations', status: 'Host plugin', description: 'Build and revise presentation decks with rendered review.' },
  { id: 'spreadsheets', name: 'Spreadsheets', status: 'Host plugin', description: 'Create, analyze, and verify spreadsheet artifacts.' },
  { id: 'sites', name: 'Sites', status: 'Host plugin', description: 'Build and host web experiences when a Sites project is present.' },
  { id: 'visualize', name: 'Visualize', status: 'Host plugin', description: 'Create interactive diagrams, simulations, plots, and visual explanations.' }
];

export const presets = [
  { id: 'lean-audit', name: 'Lean audit', skills: ['olympus-design-director', 'ui-ux', 'ux-evidence-audit', 'reference-deconstruction'] },
  { id: 'concept-lab', name: 'Concept lab', skills: ['olympus-design-director', 'ui-ux', 'ux-evidence-audit', 'reference-deconstruction', 'concept-studio', 'apple-design', 'award-rubric'] },
  { id: 'premium-build', name: 'Premium build', skills: ['olympus-design-director', 'ui-ux', 'asset-director', 'apple-design', 'awwwards-web-design', 'emil-design-eng', 'gsap-core', 'gsap-performance', 'visual-qa'] },
  { id: 'delivery-qa', name: 'Delivery QA', skills: ['olympus-design-director', 'ui-ux', 'apple-design', 'emil-design-eng', 'gsap-performance', 'design-analytics', 'visual-qa'] }
];
